### ISSUE TITLE
Advisory page 디자인 변경

### ISSUE THREAD

**Issue by kion-kqc** [Korea-Quantum-Computing/kqc-front#19]
- 자문위원 사진을 모두 수집 -> 대표님께서 수집해 주실 수 있음. 일단은 웹 상에서 괜찮은 화질로 찾아보기
- 사진 수집 후 정방 사이즈로 화질 떨어지지 않도록 맞춰야 함
- 자문위원 성함 확인
- 자문위원 현재 position 및 title 확인
- description에 초안 작성하기

data/advisory.js를 업데이트 내용 업데이트를 진행하면 됨

**Comment by HGmin1159** [comment]
넵!

**Comment by HGmin1159** [comment]
자문교수님들 홈페이지에 업데이트 했습니다. 아래와 같은 이슈가 있습니다.
다른 분들 소개글 작성해서 올렸고 사진도 정사각형으로 맞춰서 업로드 했습니다.
정인권 교수님 사진은 이학배교수님께 부탁드렸습니다. 월요일에 다시 말씀해서 받도록 하겠습니다.
3. 자문 교수님들 학력도 json으로 올렸긴 했습니다. "degree"에서 스타일 맞춰서 시험하시면 될듯 합니다.
3-1. 박성수 단장님의 경우 찾지를 못해서 degree는 못올렸습니다. 월요일에 이학배교수님께 문의하겠습니다.
